//ANIMES
export const GET_ANIMES_REQUEST = "GET_ANIMES_REQUEST";
export const GET_ANIMES_SUCCESS = "GET_ANIMES_SUCCESS";
export const GET_ANIMES_FAIL = "GET_ANIMES_FAIL";
//ANIME
export const GET_ANIME_REQUEST = "GET_ANIME_REQUEST";
export const GET_ANIME_SUCCESS = "GET_ANIME_SUCCESS";
export const GET_ANIME_FAIL = "GET_ANIME_FAIL";
//POPULAR ANIME
export const GET_POPULARS_REQUEST = "GET_POPULARS_REQUEST";
export const GET_POPULARS_SUCCESS = "GET_POPULARS_SUCCESS";
export const GET_POPULARS_FAIL = "GET_POPULARS_FAIL";
//RATED ANIME
export const GET_RATED_REQUEST = "GET_RATED_REQUEST";
export const GET_RATED_SUCCESS = "GET_RATED_SUCCESS";
export const GET_RATED_FAIL = "GET_RATED_FAIL";
//MUST watch
export const GET_BEST_ANIME_REQUEST = "GET_BEST_ANIME_REQUEST";
export const GET_BEST_ANIME_SUCCESS = "GET_BEST_ANIME_SUCCESS";
export const GET_BEST_ANIME_FAIL = "GET_BEST_ANIME_FAIL";

//LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

//SIGNUP
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
//LOGOUT
export const LOG_OUT = "LOG_OUT";

//LOAD USER
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const USER_LIKES_REQUEST = "USER_LIKES_REQUEST";
export const USER_LIKES_SUCCESS = "USER_LIKES_SUCCESS";
export const USER_LIKES_FAIL = "USER_LIKES_FAIL";

export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const DISLIKE_SUCCESS = "DISLIKE_SUCCESS";

export const ANIME_COMMENTS_REQUEST = "ANIME_COMMENTS_REQUEST";
export const ANIME_COMMENTS_SUCCESS = "ANIME_COMMENTS_SUCCESS";
export const ANIME_COMMENTS_FAIL = "ANIME_COMMENTS_FAIL";

export const USER_COMMENTS_REQUEST = "USER_COMMENTS_REQUEST";
export const USER_COMMENTS_SUCCESS = "USER_COMMENTS_SUCCESS";
export const USER_COMMENTS_FAIL = "USER_COMMENTS_FAIL";

export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";

export const USER_BOOKMARKS_REQUEST = "USER_BOOKMARKS_REQUEST";
export const USER_BOOKMARKS_SUCCESS = "USER_BOOKMARKS_SUCCESS";
export const USER_BOOKMARKS_FAIL = "USER_BOOKMARKS_FAIL";
export const ADD_BOOKMARK_SUCCESS = "ADD_BOOKMARK_SUCCESS";
export const DELETE_BOOKMARK_SUCCESS = "DELETE_BOOKMARK_SUCCESS ";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";

//Search

export const SEARCH_LOADING = "SEARCH_LOADING";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const REQUEST = "REQUEST";
export const ERROR = "ERROR";
