export const DASHBOARD_LOADING = "DASHBOARD_LOADING";
export const DASHBOARD_ERROR = "DASHBOARD_ERROR";

export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const ADD_USER = "ADD_USER";

export const ALL_ANIMES_SUCCESS = "ALL_ANIMES_SUCCESS";
export const ADD_ANIME_SUCCESS = "ADD_ANIME_SUCCESS";
export const UPDATE_ANIME_SUCCESS = "UPDATE_ANIME_SUCCESS";
export const DELETE_ANIME_SUCCESS = "DELETE_ANIME_SUCCESS";

export const ANIME_EPISODES = "ANIME_EPISODES";
export const ANIME_EPISODES_UPDATE = "ANIME_EPISODES_UPDATE";
export const ANIME_EPISODES_ADD = "ANIME_EPISODES_ADD";
export const ANIME_EPISODES_DELETE = "ANIME_EPISODES_DELETE";
